# releases the current code in the GitHub repository after all tests
# where successful.

name: Release

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
      - run: npx semantic-release
        env:
          CI: 'true'

